/* Generated by scripts/fiesta_modules.py from modules.json. Do not edit. */
#pragma once

/* clang-format off */
#ifdef __cplusplus
extern "C" {
#endif

/* Number of modules handled by SerialConfigurator. */
#define SC_MODULE_COUNT 4u

/* Module tokens: debug prefix, SerialConfigurator HELLO and firmware
 * manifests. Modules outside SerialConfigurator keep theirs here too, so
 * no token is reused by accident. */
#define SC_MODULE_TOKEN_ECU "ECU"
#define SC_MODULE_TOKEN_CLOCKS "CLOCKS"
#define SC_MODULE_TOKEN_OIL_AND_SPEED "OIL&SPD"
#define SC_MODULE_TOKEN_CLOCK "RTC_CLK"
#define SC_MODULE_TOKEN_ADJUSTOMETER "ADJ"

/* Names shown by SerialConfigurator. */
#define SC_MODULE_ECU "ECU"
#define SC_MODULE_CLOCKS "Clocks"
#define SC_MODULE_OIL_AND_SPEED "OilAndSpeed"
#define SC_MODULE_CLOCK "RTC_Clock"

#ifdef __cplusplus
}
#endif
/* clang-format on */
