/* Generated by scripts/fiesta_modules.py from modules.json. Do not edit. */
#pragma once

#include <stdbool.h>
#include <stddef.h>

#include "sc_fiesta_module_tokens.h"

/* clang-format off */
/* One X(token, display_name, source_dir, tests) row per module, in module
 * index order. The index is part of the saved flash-path schema. */
#define SC_MODULE_TABLE(X) \
  X(SC_MODULE_TOKEN_ECU, SC_MODULE_ECU, "ECU", true) \
  X(SC_MODULE_TOKEN_CLOCKS, SC_MODULE_CLOCKS, "Clocks", false) \
  X(SC_MODULE_TOKEN_OIL_AND_SPEED, SC_MODULE_OIL_AND_SPEED, "OilAndSpeed", false) \
  X(SC_MODULE_TOKEN_CLOCK, SC_MODULE_CLOCK, "Fiesta_clock", false)

/* NULL-terminated by-id name fragments of Fiesta boards that
 * SerialConfigurator does not talk to. */
#define SC_OUT_OF_SCOPE_BY_ID_HINTS {"Fiesta_Adjustometer", NULL}
/* clang-format on */
