#!/usr/bin/env python3
"""Read the Fiesta module registry (modules.json) and generate its outputs.

The registry is the only list of Fiesta modules. This script checks it and
writes the files that other tools read instead of keeping their own lists:
the C token header shared with firmware, the SerialConfigurator module table
and a Bash fragment for the shell scripts.
"""

from __future__ import annotations

import argparse
import json
import re
import shlex
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
REGISTRY_NAME = "modules.json"
SCHEMA_VERSION = 1
KINDS = ("firmware", "host-app")
ANALYSES = ("cppcheck",)
USB_VID = "0x2e8a"
USB_PID = "0x000a"
USB_PRODUCT_PREFIX = "Fiesta "
BY_ID_HINT_PREFIX = "Fiesta_"
MODULE_KEYS = {
    "name", "kind", "token", "macro", "serialConfigurator",
    "hostTests", "analysis", "ci",
}
SC_KEYS = {"index", "displayName", "tests"}

TOKENS_HEADER = Path("src/common/scDefinitions/sc_fiesta_module_tokens.h")
SC_TABLE_HEADER = Path("src/SerialConfigurator/src/core/sc_module_table.h")
SHELL_FRAGMENT = Path("src/common/scripts/fiesta-modules.sh")
GENERATED_NOTE = "Generated by scripts/fiesta_modules.py from modules.json. Do not edit."


class RegistryError(ValueError):
    """The registry or a module's project manifest breaks a registry rule."""


@dataclass(frozen=True)
class ScEntry:
    index: int
    display_name: str
    tests: bool


@dataclass(frozen=True)
class Module:
    name: str
    kind: str
    token: str | None
    macro: str | None
    serial_configurator: ScEntry | None
    host_tests: str | None
    analysis: tuple[str, ...]
    ci: bool
    by_id_hint: str | None

    @property
    def is_firmware(self) -> bool:
        return self.kind == "firmware"


@dataclass(frozen=True)
class Registry:
    modules: tuple[Module, ...]

    def firmware(self) -> list[Module]:
        return [module for module in self.modules if module.is_firmware]

    def serial_configurator(self) -> list[Module]:
        entries = [m for m in self.modules if m.serial_configurator is not None]
        return sorted(entries, key=lambda m: m.serial_configurator.index)

    def host_tests(self) -> list[Module]:
        return [module for module in self.modules if module.host_tests]

    def ci(self) -> list[Module]:
        return [module for module in self.modules if module.ci]


def _text(value: Any, where: str) -> str:
    # ASCII only: the pre-commit hook rewrites typographic punctuation, which
    # would leave the generated files out of date.
    if (not isinstance(value, str) or not value or not value.isprintable()
            or not value.isascii()):
        raise RegistryError(f"{where}: expected a non-empty printable ASCII string")
    return value


def _flag(value: Any, where: str) -> bool:
    if not isinstance(value, bool):
        raise RegistryError(f"{where}: expected true or false")
    return value


def _unique(values: list[str], what: str) -> None:
    seen: set[str] = set()
    for value in values:
        if value in seen:
            raise RegistryError(f"duplicate {what}: {value}")
        seen.add(value)


def _serial_configurator(raw: Any, where: str) -> ScEntry:
    if not isinstance(raw, dict) or set(raw) - SC_KEYS:
        raise RegistryError(f"{where}: expected keys {sorted(SC_KEYS)}")
    index = raw.get("index")
    if not isinstance(index, int) or isinstance(index, bool) or index < 0:
        raise RegistryError(f"{where}.index: expected an integer >= 0")
    return ScEntry(index, _text(raw.get("displayName"), f"{where}.displayName"),
                   _flag(raw.get("tests", False), f"{where}.tests"))


def _by_id_hint(repo_root: Path, name: str) -> str:
    """Check the USB identity in the module manifest and return its hint."""
    path = repo_root / "src" / name / ".vscode" / "jaszczurhal.project.json"
    try:
        identity = json.loads(path.read_text(encoding="utf-8"))["identity"]
    except (OSError, ValueError, KeyError, TypeError) as error:
        raise RegistryError(f"{name}: cannot read identity from {path}: {error}")
    if not isinstance(identity, dict):
        raise RegistryError(f"{name}: identity in {path} is not an object")
    if (identity.get("usbVid"), identity.get("usbPid")) != (USB_VID, USB_PID):
        raise RegistryError(f"{name}: USB VID/PID must be {USB_VID}:{USB_PID}")
    if not str(identity.get("usbProduct", "")).startswith(USB_PRODUCT_PREFIX):
        raise RegistryError(f"{name}: usbProduct must start with '{USB_PRODUCT_PREFIX}'")
    hint = str(identity.get("byIdHint", ""))
    if not hint.startswith(BY_ID_HINT_PREFIX):
        raise RegistryError(f"{name}: byIdHint must start with '{BY_ID_HINT_PREFIX}'")
    return hint


def _module(raw: Any, position: int, repo_root: Path) -> Module:
    where = f"modules[{position}]"
    if not isinstance(raw, dict):
        raise RegistryError(f"{where}: expected an object")
    unknown = set(raw) - MODULE_KEYS
    if unknown:
        raise RegistryError(f"{where}: unknown keys {sorted(unknown)}")
    name = _text(raw.get("name"), f"{where}.name")
    where = f"module {name}"
    if "/" in name or "\\" in name or not (repo_root / "src" / name).is_dir():
        raise RegistryError(f"{where}: src/{name} is not a module directory")
    kind = raw.get("kind")
    if kind not in KINDS:
        raise RegistryError(f"{where}: kind must be one of {list(KINDS)}")
    firmware = kind == "firmware"
    token = macro = hint = None
    sc_entry = None
    if firmware:
        token = _text(raw.get("token"), f"{where}.token")
        macro = _text(raw.get("macro"), f"{where}.macro")
        if not re.fullmatch(r"[A-Z][A-Z0-9_]*", macro):
            raise RegistryError(f"{where}.macro: expected an upper-case C identifier part")
        if "serialConfigurator" in raw:
            sc_entry = _serial_configurator(raw["serialConfigurator"],
                                            f"{where}.serialConfigurator")
        hint = _by_id_hint(repo_root, name)
    elif {"token", "macro", "serialConfigurator"} & set(raw):
        raise RegistryError(f"{where}: only firmware modules have token, macro "
                            "and serialConfigurator")
    host_tests = raw.get("hostTests")
    if host_tests is not None:
        host_tests = _text(host_tests, f"{where}.hostTests")
        if "/" in host_tests or "\\" in host_tests:
            raise RegistryError(f"{where}.hostTests: expected a directory name")
    analysis = raw.get("analysis", [])
    if not isinstance(analysis, list) or any(a not in ANALYSES for a in analysis):
        raise RegistryError(f"{where}.analysis: allowed values {list(ANALYSES)}")
    if analysis and host_tests is None:
        raise RegistryError(f"{where}.analysis: needs hostTests")
    return Module(name, kind, token, macro, sc_entry, host_tests, tuple(analysis),
                  _flag(raw.get("ci", True), f"{where}.ci"), hint)


def load(repo_root: Path = REPO_ROOT) -> Registry:
    """Read and check modules.json from repo_root."""
    path = repo_root / REGISTRY_NAME
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as error:
        raise RegistryError(f"cannot read {path}: {error}")
    if not isinstance(document, dict) or document.get("schemaVersion") != SCHEMA_VERSION:
        raise RegistryError(f"{path}: schemaVersion must be {SCHEMA_VERSION}")
    raw_modules = document.get("modules")
    if not isinstance(raw_modules, list) or not raw_modules:
        raise RegistryError(f"{path}: modules must be a non-empty list")
    registry = Registry(tuple(_module(raw, i, repo_root)
                              for i, raw in enumerate(raw_modules)))
    firmware = registry.firmware()
    _unique([m.name for m in registry.modules], "module name")
    _unique([m.token for m in firmware], "token")
    _unique([m.macro for m in firmware], "macro")
    _unique([m.by_id_hint for m in firmware], "byIdHint")
    for module in firmware:
        for other in firmware:
            if module is not other and module.by_id_hint in other.by_id_hint:
                raise RegistryError(f"byIdHint {module.by_id_hint} also matches "
                                    f"{other.name}")
    sc_modules = registry.serial_configurator()
    _unique([m.serial_configurator.display_name for m in sc_modules],
            "SerialConfigurator displayName")
    indices = [m.serial_configurator.index for m in sc_modules]
    if indices != list(range(len(indices))):
        raise RegistryError(f"SerialConfigurator indices must be 0..{len(indices) - 1} "
                            f"without gaps, got {indices}")
    return registry


def _c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def tokens_header(registry: Registry) -> str:
    firmware = registry.firmware()
    sc_modules = registry.serial_configurator()
    lines = [
        f"/* {GENERATED_NOTE} */",
        "#pragma once",
        "",
        "/* clang-format off */",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        "/* Number of modules handled by SerialConfigurator. */",
        f"#define SC_MODULE_COUNT {len(sc_modules)}u",
        "",
        "/* Module tokens: debug prefix, SerialConfigurator HELLO and firmware",
        " * manifests. Modules outside SerialConfigurator keep theirs here too, so",
        " * no token is reused by accident. */",
    ]
    lines += [f"#define SC_MODULE_TOKEN_{m.macro} {_c_string(m.token)}" for m in firmware]
    lines += ["", "/* Names shown by SerialConfigurator. */"]
    lines += [f"#define SC_MODULE_{m.macro} {_c_string(m.serial_configurator.display_name)}"
              for m in sc_modules]
    lines += ["", "#ifdef __cplusplus", "}", "#endif", "/* clang-format on */", ""]
    return "\n".join(lines)


def sc_table_header(registry: Registry) -> str:
    rows = [
        f"  X(SC_MODULE_TOKEN_{m.macro}, SC_MODULE_{m.macro}, {_c_string(m.name)}, "
        f"{'true' if m.serial_configurator.tests else 'false'})"
        for m in registry.serial_configurator()
    ]
    skipped = [_c_string(m.by_id_hint) for m in registry.firmware()
               if m.serial_configurator is None]
    lines = [
        f"/* {GENERATED_NOTE} */",
        "#pragma once",
        "",
        "#include <stdbool.h>",
        "#include <stddef.h>",
        "",
        '#include "sc_fiesta_module_tokens.h"',
        "",
        "/* clang-format off */",
        "/* One X(token, display_name, source_dir, tests) row per module, in module",
        " * index order. The index is part of the saved flash-path schema. */",
        "#define SC_MODULE_TABLE(X) \\",
        " \\\n".join(rows),
        "",
        "/* NULL-terminated by-id name fragments of Fiesta boards that",
        " * SerialConfigurator does not talk to. */",
        f"#define SC_OUT_OF_SCOPE_BY_ID_HINTS {{{', '.join(skipped + ['NULL'])}}}",
        "/* clang-format on */",
        "",
    ]
    return "\n".join(lines)


def _bash_array(name: str, values: list[str]) -> list[str]:
    return [f"{name}=("] + [f"    {shlex.quote(v)}" for v in values] + [")"]


def shell_fragment(registry: Registry) -> str:
    lines = [f"# {GENERATED_NOTE}", "# shellcheck shell=bash", "",
             "# Firmware modules, in registry order."]
    lines += _bash_array("FIESTA_FIRMWARE_MODULES", [m.name for m in registry.firmware()])
    lines += ["", "# Host test builds as name:source_dir:build_dir."]
    lines += _bash_array("FIESTA_HOST_TEST_MODULES", [
        f"{m.name}:src/{m.name}:src/{m.name}/{m.host_tests}"
        for m in registry.host_tests()])
    lines += ["", "# Modules whose host build has the check-cppcheck target."]
    lines += _bash_array("FIESTA_CPPCHECK_MODULES", [
        m.name for m in registry.modules if "cppcheck" in m.analysis])
    lines += ["", "fiesta_module_token_for() {", '    case "$1" in']
    lines += [f"        {shlex.quote(m.name)}) printf '%s\\n' {shlex.quote(m.token)} ;;"
              for m in registry.firmware()]
    lines += ["        *) return 1 ;;", "    esac", "}", ""]
    return "\n".join(lines)


def outputs(registry: Registry) -> dict[Path, str]:
    return {
        TOKENS_HEADER: tokens_header(registry),
        SC_TABLE_HEADER: sc_table_header(registry),
        SHELL_FRAGMENT: shell_fragment(registry),
    }


def stale_outputs(registry: Registry, repo_root: Path = REPO_ROOT) -> list[Path]:
    stale = []
    for relative, content in outputs(registry).items():
        path = repo_root / relative
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            stale.append(relative)
    return stale


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="fail when a generated file differs from modules.json")
    parser.add_argument("--repo-root", type=Path, default=REPO_ROOT,
                        help=argparse.SUPPRESS)
    args = parser.parse_args(argv)
    try:
        registry = load(args.repo_root)
    except RegistryError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    stale = stale_outputs(registry, args.repo_root)
    if args.check:
        for path in stale:
            print(f"error: {path} is out of date; run scripts/fiesta_modules.py",
                  file=sys.stderr)
        return 1 if stale else 0
    for relative in stale:
        path = args.repo_root / relative
        with path.open("w", encoding="utf-8", newline="\n") as handle:
            handle.write(outputs(registry)[relative])
        print(f"generated {relative}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
